#!/usr/bin/env python3
"""Git コミット & プッシュ（PR なしでも可）"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

from lib.config import get_session_dir, load_config  # noqa: E402


def run_git(args: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git"] + args,
        cwd=str(cwd or ROOT),
        capture_output=True,
        text=True,
    )


def resolve_deploy_rel(target: dict) -> str:
    try:
        config = load_config()
        wp = config.get("wordpress", {})
        theme_path = wp.get(
            "theme_path",
            f"wp-content/themes/{target.get('theme_slug', 'swell-child')}",
        )
        if target.get("parent_theme") == "swell" or target.get("theme_slug", "").endswith("-child"):
            theme_path = wp.get(
                "swell_child_path",
                f"wp-content/themes/{target.get('theme_slug', 'swell-child')}",
            )
    except FileNotFoundError:
        theme_path = f"wp-content/themes/{target.get('theme_slug', 'swell-child')}"

    if target.get("type") == "block":
        block_name = target.get("block_name", "block")
        return f"{theme_path}/blocks/{block_name}"
    return theme_path


def stage_wordpress(session_id: str) -> dict:
    session_dir = get_session_dir(session_id)
    task_path = session_dir / "task.json"
    wp_dir = session_dir / "wordpress"
    if not task_path.exists():
        return {"success": False, "error": "task.json が見つかりません"}
    if not wp_dir.exists():
        return {"success": False, "error": "wordpress/ が見つかりません"}

    task = json.loads(task_path.read_text(encoding="utf-8"))
    target = task.get("manifest", {}).get("target", {})
    deploy_rel = resolve_deploy_rel(target)
    deploy_dir = ROOT / "wp-content-staging" / deploy_rel
    deploy_dir.parent.mkdir(parents=True, exist_ok=True)
    if deploy_dir.exists():
        shutil.rmtree(deploy_dir)
    shutil.copytree(
        wp_dir,
        deploy_dir,
        ignore=shutil.ignore_patterns("preview.html"),
    )
    return {
        "success": True,
        "deploy_rel": deploy_rel,
        "deploy_dir": str(deploy_dir),
        "target": target,
        "task": task,
    }


def commit_and_push(
    session_id: str,
    *,
    message: str | None = None,
    branch: str | None = None,
    push: bool = True,
    create_pr: bool = False,
    base: str = "staging",
) -> dict:
    staged = stage_wordpress(session_id)
    if not staged.get("success"):
        return staged

    target = staged["target"]
    deploy_rel = staged["deploy_rel"]
    branch_name = branch or f"wpai/{session_id}"
    commit_msg = message or (
        f"feat(swell): {target.get('type', 'update')} - {session_id}\n\n"
        f"Theme: {target.get('theme_slug', 'swell-child')}\n"
        f"Parent: {target.get('parent_theme', 'swell')}\n"
        f"Auto-generated by WPAIPublisher"
    )

    run_git(["checkout", "-B", branch_name])
    add_path = str((ROOT / "wp-content-staging" / deploy_rel).relative_to(ROOT))
    run_git(["add", "-A", add_path])

    # レポートも同梱（任意）
    report = get_session_dir(session_id) / "change_report.md"
    if report.exists():
        reports_dir = ROOT / "wp-content-staging" / "reports" / session_id
        reports_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(report, reports_dir / "change_report.md")
        run_git(["add", "-A", str(reports_dir.relative_to(ROOT))])

    status = run_git(["status", "--porcelain"])
    if not status.stdout.strip():
        result = {
            "success": True,
            "branch": branch_name,
            "deploy_path": deploy_rel,
            "message": "変更なし",
            "pushed": False,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
    else:
        commit = run_git(["commit", "-m", commit_msg])
        if commit.returncode != 0 and "nothing to commit" not in (commit.stdout + commit.stderr):
            return {"success": False, "error": commit.stderr or commit.stdout, "branch": branch_name}

        result = {
            "success": True,
            "branch": branch_name,
            "deploy_path": deploy_rel,
            "commit_message": commit_msg.split("\n", 1)[0],
            "pushed": False,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

        if push:
            push_result = run_git(["push", "-u", "origin", branch_name])
            if push_result.returncode != 0:
                result["success"] = False
                result["error"] = f"push failed: {push_result.stderr}"
                result["pushed"] = False
            else:
                result["pushed"] = True

    if create_pr and result.get("success") and result.get("pushed"):
        sys.path.insert(0, str(ROOT / "scripts" / "git"))
        from create_pr import create_pr as make_pr  # noqa: E402

        pr = make_pr(session_id, base)
        result["pr"] = pr

    out = get_session_dir(session_id) / "git_push.json"
    out.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Git コミット & プッシュ")
    parser.add_argument("session_id")
    parser.add_argument("--message", "-m", help="コミットメッセージ")
    parser.add_argument("--branch", help="ブランチ名（省略時 wpai/<session>）")
    parser.add_argument("--no-push", action="store_true", help="コミットのみ")
    parser.add_argument("--pr", action="store_true", help="続けて PR 作成")
    parser.add_argument("--base", default="staging")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    result = commit_and_push(
        args.session_id,
        message=args.message,
        branch=args.branch,
        push=not args.no_push,
        create_pr=args.pr,
        base=args.base,
    )

    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        if result.get("success"):
            print(f"Git OK: {result.get('branch')}")
            print(f"  path: {result.get('deploy_path')}")
            print(f"  pushed: {result.get('pushed')}")
            if result.get("message"):
                print(f"  note: {result['message']}")
            if result.get("pr", {}).get("pr_url"):
                print(f"  PR: {result['pr']['pr_url']}")
        else:
            print(f"ERROR: {result.get('error')}", file=sys.stderr)
    return 0 if result.get("success") else 1


if __name__ == "__main__":
    sys.exit(main())
