#!/usr/bin/env python3
"""Git Pull Request 作成"""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

from lib.config import get_session_dir, load_config  # noqa: E402


def run_git(args: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git"] + args,
        cwd=str(cwd or ROOT),
        capture_output=True,
        text=True,
    )


def create_pr(session_id: str, base_branch: str = "staging") -> dict:
    session_dir = get_session_dir(session_id)
    task_path = session_dir / "task.json"
    if not task_path.exists():
        return {"success": False, "error": "task.json が見つかりません"}

    task = json.loads(task_path.read_text(encoding="utf-8"))
    manifest = task.get("manifest", {})
    target = manifest.get("target", {})
    branch_name = f"wpai/{session_id}"

    wp_dir = session_dir / "wordpress"
    if not wp_dir.exists():
        return {"success": False, "error": "wordpress/ が見つかりません"}

    try:
        config = load_config()
        theme_path = config.get("wordpress", {}).get("theme_path", "wp-content/themes/custom-theme")
    except FileNotFoundError:
        theme_path = "wp-content/themes/custom-theme"

    # デプロイ先パスを決定
    if target.get("type") == "block":
        block_name = target.get("block_name", "block")
        deploy_rel = f"{theme_path}/blocks/{block_name}"
    else:
        deploy_rel = theme_path

    deploy_dir = ROOT / "wp-content-staging" / deploy_rel
    deploy_dir.parent.mkdir(parents=True, exist_ok=True)

    # wordpress/ を Git 管理ディレクトリへコピー
    import shutil
    if deploy_dir.exists():
        shutil.rmtree(deploy_dir)
    shutil.copytree(wp_dir, deploy_dir)

    # Git操作
    status = run_git(["status", "--porcelain"])
    if not status.stdout.strip() and run_git(["branch", "--list", branch_name]).stdout.strip():
        return {"success": True, "branch": branch_name, "message": "変更なし（既存ブランチ）"}

    run_git(["checkout", "-B", branch_name])
    run_git(["add", str(deploy_dir.relative_to(ROOT))])

    commit_msg = (
        f"feat(wpai): {target.get('type', 'update')} - {session_id}\n\n"
        f"Source: {manifest.get('source', {}).get('tool', 'unknown')}\n"
        f"Auto-generated by WPAIPublisher"
    )
    commit = run_git(["commit", "-m", commit_msg])
    if commit.returncode != 0 and "nothing to commit" not in commit.stdout + commit.stderr:
        return {"success": False, "error": commit.stderr}

    push = run_git(["push", "-u", "origin", branch_name])
    if push.returncode != 0:
        return {"success": False, "error": f"push failed: {push.stderr}", "branch": branch_name}

    # gh CLI でPR作成
    pr_title = f"[WPAI] {target.get('type', 'update')}: {session_id}"
    pr_body = f"""## WPAIPublisher 自動PR

- **Session**: {session_id}
- **Target**: {target.get('type')} / {target.get('block_name', target.get('page_slug', ''))}
- **Source AI**: {manifest.get('source', {}).get('tool', 'unknown')}

## 品質ゲート
品質ゲート結果は `output/{session_id}/quality_gates.json` を参照

## チェックリスト
- [ ] 品質ゲート通過
- [ ] ビジュアル回帰テスト通過
- [ ] ステージング確認済み
"""

    pr_result = subprocess.run(
        ["gh", "pr", "create", "--base", base_branch, "--head", branch_name,
         "--title", pr_title, "--body", pr_body],
        capture_output=True, text=True, cwd=str(ROOT),
    )

    result = {
        "success": True,
        "branch": branch_name,
        "deploy_path": str(deploy_rel),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    if pr_result.returncode == 0:
        result["pr_url"] = pr_result.stdout.strip()
    else:
        result["pr_warning"] = pr_result.stderr.strip() or "gh CLI未設定。手動でPRを作成してください"

    # 記録
    record_path = session_dir / "git_pr.json"
    record_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Git Pull Request 作成")
    parser.add_argument("session_id", help="セッションID")
    parser.add_argument("--base", default="staging", help="ベースブランチ")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    result = create_pr(args.session_id, args.base)

    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        if result.get("success"):
            print(f"PR作成: {result.get('branch')}")
            if result.get("pr_url"):
                print(f"URL: {result['pr_url']}")
            if result.get("pr_warning"):
                print(f"WARN: {result['pr_warning']}")
        else:
            print(f"ERROR: {result.get('error')}", file=sys.stderr)

    return 0 if result.get("success") else 1


if __name__ == "__main__":
    sys.exit(main())
