#!/usr/bin/env python3
"""SWELL 対応コードへの自動変換（子テーマ・テンプレート・ブロック振り分け）"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from dataclasses import asdict
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

from analyze.html_structure import analyze_session  # noqa: E402
from lib.config import get_session_dir  # noqa: E402


def slugify(text: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_-]+", "-", text.strip().lower()).strip("-")
    return s or "section"


def esc_php(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "\\'")


class BodyExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self._in_body = False
        self._parts: list[str] = []
        self._depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "body":
            self._in_body = True
            self._depth = 1
            return
        if not self._in_body:
            return
        attr_str = "".join(
            f' {k}="{v}"' if v is not None else f" {k}" for k, v in attrs
        )
        self._parts.append(f"<{tag}{attr_str}>")
        if tag not in {"br", "img", "hr", "meta", "link", "input"}:
            self._depth += 1

    def handle_endtag(self, tag: str) -> None:
        if tag == "body":
            self._in_body = False
            return
        if not self._in_body:
            return
        self._parts.append(f"</{tag}>")
        self._depth = max(0, self._depth - 1)

    def handle_data(self, data: str) -> None:
        if self._in_body:
            self._parts.append(data)

    def get_body(self) -> str:
        return "".join(self._parts).strip()


def extract_body(html: str) -> str:
    p = BodyExtractor()
    p.feed(html)
    body = p.get_body()
    if body:
        return body
    # body タグが無い場合は全体から script/style/head を除く簡易版
    cleaned = re.sub(r"(?is)<script[^>]*>.*?</script>", "", html)
    cleaned = re.sub(r"(?is)<style[^>]*>.*?</style>", "", cleaned)
    cleaned = re.sub(r"(?is)<head[^>]*>.*?</head>", "", cleaned)
    cleaned = re.sub(r"(?is)</?html[^>]*>", "", cleaned)
    cleaned = re.sub(r"(?is)</?body[^>]*>", "", cleaned)
    return cleaned.strip()


def write_child_theme_scaffold(dest: Path, theme_slug: str, parent: str = "swell") -> None:
    dest.mkdir(parents=True, exist_ok=True)
    style = f"""/*
Theme Name: {theme_slug}
Template: {parent}
Description: WPAIPublisher generated SWELL child theme
Version: 1.0.0
Text Domain: {theme_slug}
*/

/* WPAIPublisher generated styles */
"""
    (dest / "style.css").write_text(style, encoding="utf-8")
    functions = f"""<?php
/**
 * {theme_slug} — SWELL child theme functions
 * Auto-generated by WPAIPublisher
 */
if ( ! defined( 'ABSPATH' ) ) {{
\texit;
}}

add_action( 'wp_enqueue_scripts', '{theme_slug.replace("-", "_")}_enqueue_assets', 20 );
function {theme_slug.replace("-", "_")}_enqueue_assets() {{
\twp_enqueue_style(
\t\t'{theme_slug}-style',
\t\tget_stylesheet_uri(),
\t\tarray( 'main_style' ),
\t\twp_get_theme()->get( 'Version' )
\t);
\t$custom_css = get_stylesheet_directory() . '/assets/css/wpaipublisher.css';
\tif ( file_exists( $custom_css ) ) {{
\t\twp_enqueue_style(
\t\t\t'{theme_slug}-wpaipublisher',
\t\t\tget_stylesheet_directory_uri() . '/assets/css/wpaipublisher.css',
\t\t\tarray( '{theme_slug}-style' ),
\t\t\tfilemtime( $custom_css )
\t\t);
\t}}
\t$custom_js = get_stylesheet_directory() . '/assets/js/wpaipublisher.js';
\tif ( file_exists( $custom_js ) ) {{
\t\twp_enqueue_script(
\t\t\t'{theme_slug}-wpaipublisher',
\t\t\tget_stylesheet_directory_uri() . '/assets/js/wpaipublisher.js',
\t\t\tarray(),
\t\t\tfilemtime( $custom_js ),
\t\t\ttrue
\t\t);
\t}}
}}

// Register custom blocks generated by WPAIPublisher
$blocks_dir = get_stylesheet_directory() . '/blocks';
if ( is_dir( $blocks_dir ) ) {{
\tforeach ( glob( $blocks_dir . '/*/block.json' ) as $block_json ) {{
\t\tregister_block_type( dirname( $block_json ) );
\t}}
}}
"""
    (dest / "functions.php").write_text(functions, encoding="utf-8")
    (dest / "assets" / "css").mkdir(parents=True, exist_ok=True)
    (dest / "assets" / "js").mkdir(parents=True, exist_ok=True)
    (dest / "blocks").mkdir(parents=True, exist_ok=True)
    (dest / "template-parts").mkdir(parents=True, exist_ok=True)
    (dest / "templates").mkdir(parents=True, exist_ok=True)


def generate_block(block_dir: Path, block_name: str, theme_slug: str, html: str, css: str = "") -> None:
    block_dir.mkdir(parents=True, exist_ok=True)
    full_name = f"{theme_slug}/{block_name}"
    block_json = {
        "$schema": "https://schemas.wp.org/trunk/block.json",
        "apiVersion": 3,
        "name": full_name,
        "title": block_name.replace("-", " ").title(),
        "category": "theme",
        "icon": "layout",
        "supports": {"html": False, "align": ["wide", "full"]},
        "textdomain": theme_slug,
        "style": "file:./style.css",
        "render": "file:./render.php",
    }
    (block_dir / "block.json").write_text(
        json.dumps(block_json, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    render = f"""<?php
/**
 * SWELL child block: {full_name}
 * @var array    $attributes
 * @var string   $content
 * @var WP_Block $block
 */
if ( ! defined( 'ABSPATH' ) ) {{
\texit;
}}
$wrapper = get_block_wrapper_attributes( array( 'class' => 'wpaip-{block_name}' ) );
?>
<div <?php echo $wrapper; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
{html}
</div>
"""
    (block_dir / "render.php").write_text(render, encoding="utf-8")
    (block_dir / "style.css").write_text(
        css or f".wpaip-{block_name} {{ /* generated */ }}\n",
        encoding="utf-8",
    )


def generate_template_part(parts_dir: Path, name: str, html: str) -> None:
    parts_dir.mkdir(parents=True, exist_ok=True)
    php = f"""<?php
/**
 * Template part: {name}
 * SWELL child theme — WPAIPublisher
 */
if ( ! defined( 'ABSPATH' ) ) {{
\texit;
}}
?>
{html}
"""
    (parts_dir / f"{name}.php").write_text(php, encoding="utf-8")


def generate_page_template(templates_dir: Path, slug: str, title: str, block_refs: list[str], theme_slug: str) -> None:
    templates_dir.mkdir(parents=True, exist_ok=True)
    blocks_html = "\n".join(
        f'<!-- wp:{theme_slug}/{b} /-->' for b in block_refs
    )
    content = f"""<!-- wp:group {{"tagName":"main","className":"wpaip-page-{slug}"}} -->
<div class="wp-block-group wpaip-page-{slug}">
{blocks_html}
</div>
<!-- /wp:group -->
"""
    (templates_dir / f"page-{slug}.html").write_text(content, encoding="utf-8")
    # プレビュー用
    preview = f"""<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<title>{title or slug}</title>
<link rel="stylesheet" href="../style.css">
<link rel="stylesheet" href="../assets/css/wpaipublisher.css">
</head>
<body class="swell-child preview">
<main class="wpaip-page-{slug}">
<!-- blocks: {', '.join(block_refs)} -->
<p>SWELL child theme preview for <strong>{slug}</strong></p>
</main>
</body>
</html>
"""
    (templates_dir.parent / "preview.html").write_text(preview, encoding="utf-8")


def convert_session(
    session_id: str,
    *,
    theme_slug: str = "swell-child",
    parent_theme: str = "swell",
) -> dict[str, Any]:
    session_dir = get_session_dir(session_id)
    source = session_dir / "source"
    if not source.exists():
        raise FileNotFoundError(f"source/ がありません: {session_dir}")

    structure_path = session_dir / "structure.json"
    if structure_path.exists():
        structure = json.loads(structure_path.read_text(encoding="utf-8"))
    else:
        structure = asdict(analyze_session(session_id))

    wp = session_dir / "wordpress"
    if wp.exists():
        shutil.rmtree(wp)
    write_child_theme_scaffold(wp, theme_slug, parent_theme)

    # CSS / JS 統合
    css_parts: list[str] = []
    js_parts: list[str] = []
    for css in source.rglob("*.css"):
        css_parts.append(f"/* {css.name} */\n{css.read_text(encoding='utf-8', errors='ignore')}\n")
    for js in source.rglob("*.js"):
        js_parts.append(f"/* {js.name} */\n{js.read_text(encoding='utf-8', errors='ignore')}\n")
    (wp / "assets" / "css" / "wpaipublisher.css").write_text(
        "\n".join(css_parts) or "/* no source css */\n", encoding="utf-8"
    )
    (wp / "assets" / "js" / "wpaipublisher.js").write_text(
        "\n".join(js_parts) or "/* no source js */\n", encoding="utf-8"
    )

    html_files = sorted(source.rglob("*.html"))
    block_names: list[str] = []
    template_parts: list[str] = []
    page_slug = "home"

    task_path = session_dir / "task.json"
    task = json.loads(task_path.read_text(encoding="utf-8")) if task_path.exists() else {}
    manifest = task.get("manifest", {})
    target = manifest.get("target", {})
    page_slug = target.get("page_slug") or slugify(structure.get("title") or "home")

    # コンポーネント振り分け
    components = structure.get("components") or []
    # HTML 全体も page-content / blocks に落とす
    for html_path in html_files:
        body = extract_body(html_path.read_text(encoding="utf-8", errors="ignore"))
        stem = slugify(html_path.stem)

        # ファイル単位の主要ブロック
        block_name = stem
        generate_block(
            wp / "blocks" / block_name,
            block_name,
            theme_slug,
            body,
            css="",
        )
        block_names.append(block_name)

    # structure に基づく template-part
    for comp in components:
        kind = comp.get("kind")
        target_type = comp.get("swell_target")
        if target_type != "template-part":
            continue
        name = slugify(kind or "part")
        if name in template_parts:
            continue
        preview = comp.get("text_preview") or kind
        generate_template_part(
            wp / "template-parts",
            name,
            f'<div class="wpaip-part-{name}">{preview}</div>\n',
        )
        template_parts.append(name)

    generate_page_template(
        wp / "templates",
        page_slug,
        structure.get("title") or page_slug,
        block_names,
        theme_slug,
    )

    # content.html（REST ページ投入用）
    content_blocks = "\n".join(f'<!-- wp:{theme_slug}/{b} /-->' for b in block_names)
    (wp / "content.html").write_text(content_blocks + "\n", encoding="utf-8")

    # 変換メタ
    conversion = {
        "engine": "swell",
        "parent_theme": parent_theme,
        "theme_slug": theme_slug,
        "page_slug": page_slug,
        "blocks": block_names,
        "template_parts": template_parts,
        "routing": structure.get("routing", {}),
        "converted_at": datetime.now(timezone.utc).isoformat(),
        "source_files": [str(p.relative_to(source)) for p in html_files],
    }
    (session_dir / "swell_conversion.json").write_text(
        json.dumps(conversion, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    # task.json 更新
    if task_path.exists():
        task["status"] = "converted"
        task["converted_at"] = conversion["converted_at"]
        task["conversion_engine"] = "swell"
        task.setdefault("manifest", {}).setdefault("target", {})
        task["manifest"]["target"]["type"] = target.get("type") or "page"
        task["manifest"]["target"]["theme_slug"] = theme_slug
        task["manifest"]["target"]["parent_theme"] = parent_theme
        task["manifest"]["target"]["page_slug"] = page_slug
        task_path.write_text(json.dumps(task, indent=2, ensure_ascii=False), encoding="utf-8")
        try:
            from lib.sync_hook import sync_session  # noqa: E402

            sync_session(session_id)
        except Exception:  # noqa: BLE001
            pass

    # 簡易 validation.json（後続 validate でも上書き可）
    validation = {
        "valid": True,
        "session_id": session_id,
        "engine": "swell",
        "checks": [
            {"name": "wordpress_dir", "passed": wp.exists()},
            {"name": "style_css", "passed": (wp / "style.css").exists()},
            {"name": "functions_php", "passed": (wp / "functions.php").exists()},
            {"name": "blocks", "passed": bool(block_names)},
        ],
        "timestamp": conversion["converted_at"],
    }
    validation["valid"] = all(c["passed"] for c in validation["checks"])
    (session_dir / "validation.json").write_text(
        json.dumps(validation, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    return conversion


def main() -> int:
    parser = argparse.ArgumentParser(description="SWELL 対応コードへ変換")
    parser.add_argument("session_id")
    parser.add_argument("--theme-slug", default="swell-child")
    parser.add_argument("--parent-theme", default="swell")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    try:
        result = convert_session(
            args.session_id,
            theme_slug=args.theme_slug,
            parent_theme=args.parent_theme,
        )
    except Exception as e:  # noqa: BLE001
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print(f"SWELL conversion OK: {args.session_id}")
        print(f"  theme: {result['theme_slug']} (parent: {result['parent_theme']})")
        print(f"  blocks: {', '.join(result['blocks']) or '-'}")
        print(f"  template-parts: {', '.join(result['template_parts']) or '-'}")
        print(f"  page: {result['page_slug']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
